export const Users = [
  {
    id: 1,
    profilePicture: "person/Person1.jpg",
    username: "Linh Anna",
  },
  {
    id: 2,
    profilePicture: "person/Person2.jpg",
    username: "Elizabeth",
  },
  {
    id: 3,
    profilePicture: "person/Person3.jpg",
    username: "Connor",
  },
  {
    id: 4,
    profilePicture: "person/Person4.jpg",
    username: "Olivia",
  },
  {
    id: 5,
    profilePicture: "person/Person5.jpg",
    username: "Liam",
  },
  {
    id: 6,
    profilePicture: "person/Person6.jpg",
    username: "Sophia",
  },
  {
    id: 7,
    profilePicture: "person/Person7.jpg",
    username: "William",
  },
  {
    id: 8,
    profilePicture: "person/Person8.jpg",
    username: "Amelia",
  },
  {
    id: 9,
    profilePicture: "person/Person9.jpg",
    username: "Lucas",
  },
  {
    id: 10,
    profilePicture: "person/Person10.jpg",
    username: "Mia",
  },
];
export const Posts = [
  {
    id: 1,
    description: "Take a look at this holy golden bridge!",
    photo: "post/Post1.jpg",
    date: "3 mins ago",
    userId: 1,
    like: 24,
    comment: 12,
  },
  {
    id: 2,
    description: "I'm having fun and relaxing at this beautiful beach ",
    photo: "post/Post2.jpg",
    date: "20 mins ago",
    userId: 2,
    like: 36,
    comment: 8,
  },
  {
    id: 3,
    description: "I'm learning about these ancient rocks",
    photo: "post/Post3.jpg",
    date: "20 mins ago",
    userId: 3,
    like: 6,
    comment: 5,
  },
  {
    id: 4,
    description: "I'm greatly motivated by this quote right now",
    photo: "post/Post4.jpg",
    date: "1 mins ago",
    userId: 4,
    like: 95,
    comment: 57,
  },
  {
    id: 5,
    description: "I'm excited!",
    photo: "post/Post5.jpg",
    date: "39 mins ago",
    userId: 5,
    like: 67,
    comment: 46,
  },
  {
    id: 6,
    description: "Having a delicious and healthy breakfast!",
    photo: "post/Post6.jpg",
    date: "15 mins ago",
    userId: 6,
    like: 76,
    comment: 47,
  },
  {
    id: 7,
    description: "I'm having a blast with my friends at the water park!",
    photo: "post/Post7.jpg",
    date: "24 mins ago",
    userId: 7,
    like: 85,
    comment: 68,
  },
  {
    id: 8,
    description: "I'm stunned by this majestic tiger!",
    photo: "post/Post8.jpeg",
    date: "1 hour ago",
    userId: 8,
    like: 120,
    comment: 90,
  },
  {
    id: 9,
    description: "Look at those extremely beautiful and colorful flowers!",
    photo: "post/Post9.jpg",
    date: "59 mins ago",
    userId: 9,
    like: 63,
    comment: 36,
  },
  {
    id: 10,
    description: "Buying this baby!",
    photo: "post/Post10.jpg",
    date: "5 hours ago",
    userId: 10,
    like: 160,
    comment: 100,
  },
];
